name: Check

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Docs
        run: pnpm run docs:build
