name: 'Release(master)'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Prepare
        run: |
          npm i pnpm@latest -g
          pnpm install
          pnpm test
          pnpm run build
          pnpm run docs:build

      - name: Publish NPM
        run: |
          pnpm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          pnpm publish --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH }}
